# Generated by Django 3.0.3 on 2020-03-02 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200302_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='dob',
            field=models.DateField(),
        ),
    ]
